export const TIPOS_USUARIO = [
  { value: "PRODUTOR_ESTRADA", label: "Produtor de Estrada" },
  { value: "PRE_PRODUTOR", label: "Pré-Produtor" },
  { value: "PRODUTOR", label: "Produtor" },
  { value: "TECNICO_SOM", label: "Técnico de Som" },
  { value: "TECNICO_LUZ", label: "Técnico de Luz" },
  { value: "TECNICO_MONITOR", label: "Técnico de Monitor" },
  { value: "TECNICO_PA", label: "Técnico de PA" },
  { value: "ROAD", label: "Roadie" },
  { value: "ARTISTA", label: "Artista" },
  // Tipos de músicos mapeados
  { value: "GUITARRISTA", label: "Guitarrista" },
  { value: "BAIXISTA", label: "Baixista" },
  { value: "BATERISTA", label: "Baterista" },
  { value: "TECLADISTA", label: "Tecladista" },
  { value: "VIOLONISTA", label: "Violonista" },
  { value: "VOCALISTA", label: "Vocalista" },
  { value: "SAXOFONISTA", label: "Saxofonista" },
  { value: "TROMPETISTA", label: "Trompetista" },
  { value: "TROMBONISTA", label: "Trombonista" },
  { value: "PERCUSSIONISTA", label: "Percussionista" },
  { value: "VIOLINISTA", label: "Violinista" },
  { value: "CELISTA", label: "Celista" },
  { value: "CONTRABAIXISTA", label: "Contrabaixista" },
  { value: "FLAUTISTA", label: "Flautista" },
  { value: "CLARINETISTA", label: "Clarinetista" },
  { value: "OBOISTA", label: "Oboísta" },
  { value: "FAGOTISTA", label: "Fagotista" },
  { value: "HARPISTA", label: "Harpista" },
  { value: "PIANISTA", label: "Pianista" },
  { value: "ACORDEONISTA", label: "Acordeonista" },
  { value: "GAITEIRO", label: "Gaiteiro" },
  { value: "BANDOLINISTA", label: "Bandolinista" },
  { value: "CAVAQUINISTA", label: "Cavaquinista" },
  { value: "UKULELISTA", label: "Ukulelista" },
  { value: "GUITARRA_RITMICA", label: "Guitarra Rítmica" },
  { value: "GUITARRA_SOLO", label: "Guitarra Solo" },
  { value: "DJ", label: "DJ" },
  { value: "MC", label: "MC" },
  { value: "REGENTE", label: "Regente" },
  { value: "MAESTRO", label: "Maestro" },
  { value: "ARRANJADOR", label: "Arranjador" },
  { value: "COMPOSITOR", label: "Compositor" },
  { value: "LETRISTA", label: "Letrista" },
  { value: "PRODUTOR_MUSICAL", label: "Produtor Musical" },
  { value: "ENGENHEIRO_SOM", label: "Engenheiro de Som" },
  { value: "BACKING_VOCAL", label: "Backing Vocal" },
  { value: "CORISTA", label: "Corista" },
  { value: "RAPPER", label: "Rapper" },
  { value: "VIOLISTA", label: "Violista" },
  { value: "TUBISTA", label: "Tubista" },
  { value: "SAX_BARITONO", label: "Sax Barítono" },
  { value: "SAX_TENOR", label: "Sax Tenor" },
  { value: "SAX_ALTO", label: "Sax Alto" },
  { value: "SAX_SOPRANO", label: "Sax Soprano" },
  { value: "TROMPA", label: "Trompa" },
  { value: "EUPHONIUM", label: "Euphonium" },
  { value: "TIMPANISTA", label: "Timpanista" },
  { value: "MARIMBISTA", label: "Marimbista" },
  { value: "XYLOFONISTA", label: "Xilofonista" },
  { value: "VIBRAFONISTA", label: "Vibrafonista" },
  { value: "TRIANGULISTA", label: "Triangulista" },
  { value: "CANTOR_LIRICO", label: "Cantor Lírico" },
  { value: "SOPRANO", label: "Soprano" },
  { value: "CONTRALTO", label: "Contralto" },
  { value: "TENOR", label: "Tenor" },
  { value: "BARITONO", label: "Barítono" },
  { value: "BAIXO", label: "Baixo" },
];