export const TIPOS_USUARIO = [
  { value: "produtorEstrada", label: "Produtor de Estrada" },
  { value: "preProdutor", label: "Pré-Produtor" },
  { value: "produtor", label: "Produtor" },
  { value: "tecnicoSom", label: "Técnico de Som" },
  { value: "tecnicoLuz", label: "Técnico de Luz" },
  { value: "tecnicoMonitor", label: "Técnico de Monitor" },
  { value: "tecnicoPA", label: "Técnico de PA" },
  { value: "road", label: "Roadie" },
  { value: "artista", label: "Artista" },

  // Tipos de músicos mapeados
  { value: "guitarrista", label: "Guitarrista" },
  { value: "baixista", label: "Baixista" },
  { value: "baterista", label: "Baterista" },
  { value: "tecladista", label: "Tecladista" },
  { value: "violonista", label: "Violonista" },
  { value: "vocalista", label: "Vocalista" },
  { value: "saxofonista", label: "Saxofonista" },
  { value: "trompetista", label: "Trompetista" },
  { value: "trombonista", label: "Trombonista" },
  { value: "percussionista", label: "Percussionista" },
  { value: "violinista", label: "Violinista" },
  { value: "celista", label: "Celista" },
  { value: "contrabaixista", label: "Contrabaixista" },
  { value: "flautista", label: "Flautista" },
  { value: "clarinetista", label: "Clarinetista" },
  { value: "oboista", label: "Oboísta" },
  { value: "fagotista", label: "Fagotista" },
  { value: "harpista", label: "Harpista" },
  { value: "pianista", label: "Pianista" },
  { value: "acordeonista", label: "Acordeonista" },
  { value: "gaiteiro", label: "Gaiteiro" },
  { value: "bandolinista", label: "Bandolinista" },
  { value: "cavaquinista", label: "Cavaquinista" },
  { value: "ukulelista", label: "Ukulelista" },
  { value: "guitarraRitmica", label: "Guitarra Rítmica" },
  { value: "guitarraSolo", label: "Guitarra Solo" },
  { value: "dj", label: "DJ" },
  { value: "mc", label: "MC" },
  { value: "regente", label: "Regente" },
  { value: "maestro", label: "Maestro" },
  { value: "arranjador", label: "Arranjador" },
  { value: "compositor", label: "Compositor" },
  { value: "letrista", label: "Letrista" },
  { value: "produtorMusical", label: "Produtor Musical" },
  { value: "engenheiroSom", label: "Engenheiro de Som" },
  { value: "backingVocal", label: "Backing Vocal" },
  { value: "corista", label: "Corista" },
  { value: "rapper", label: "Rapper" },
  { value: "violista", label: "Violista" },
  { value: "tubista", label: "Tubista" },
  { value: "saxBaritono", label: "Sax Barítono" },
  { value: "saxTenor", label: "Sax Tenor" },
  { value: "saxAlto", label: "Sax Alto" },
  { value: "saxSoprano", label: "Sax Soprano" },
  { value: "trompa", label: "Trompa" },
  { value: "euphonium", label: "Euphonium" },
  { value: "timpanista", label: "Timpanista" },
  { value: "marimbista", label: "Marimbista" },
  { value: "xilofonista", label: "Xilofonista" },
  { value: "vibrafonista", label: "Vibrafonista" },
  { value: "triangulista", label: "Triangulista" },
  { value: "cantorLirico", label: "Cantor Lírico" },
  { value: "soprano", label: "Soprano" },
  { value: "contralto", label: "Contralto" },
  { value: "tenor", label: "Tenor" },
  { value: "baritono", label: "Barítono" },
  { value: "baixo", label: "Baixo" },
];
